#Prometheus Config
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'Auto-SRE'
    static_configs:
      - targets: ['api:8000'] #'api' linked from docker compose
